services:
  app:
    build: .
    container_name: app
    ports:
      - "8000:8000"
    volumes:
      - ./static:/app/static
      - ./images:/app/images
    networks:
      - app_network

  nginx:
    image: nginx
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./static:/usr/share/nginx/html
      - ./images:/images
    networks:
      - app_network
    depends_on:
      - app

networks:
  app_network:



