services:
  app:
    build: .
    container_name: app
    ports:
      - "8000:8000"
    volumes:
      - ./static:/app/static
      - ./images:/app/images
      - ./logs:/app/logs
    networks:
      - app_network
      - db_network
    depends_on:
      - db

  nginx:
    image: nginx
    restart: always
    container_name: nginx
    command: nginx -g "daemon off;"
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./static:/usr/share/nginx/html
      - ./images:/images
      - ./logs:/var/log/nginx
    networks:
      - app_network
    depends_on:
      - app

  db:
    image: postgres:17-alpine
    container_name: db
    environment:
      POSTGRES_DB: images_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    networks:
      - db_network
    volumes:
      - db_data:/var/lib/postgresql/data

networks:
  app_network:
  db_network:

volumes:
  db_data:



